project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: 
    Course Projects for STA 9750 at Baruch College
  site-url: "https://siya306.github.io/STA9750-2025-FALL/"
  navbar:
    background: light
    left:
      - text: "Home"
        href: index.qmd
      - text: "MP01"
        href: mp01.qmd
  page-footer:
    center: "© 2025 | STA 9750 | Quarto + GitHub Pages"
format:
  html:
    theme: sandstone
    toc: false

editor:
  mode: source
